Bi3Smart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/",include("userauths.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import index,chat,update_item_from_cart,delete_item_from_cart,cart_view,add_to_cart,filter_product,search_view,ajax_add_review,tag_list,product_list_view,category_list_view,category_product_list_view, vendor_detail_view,vendor_list_view,product_detail_view
app_name= "core"

urlpatterns = [
    #chatbot
    path('chat/', chat, name='chat'),

    #HomePage
    path("",index , name="index"),
    #Product
    path("products/" , product_list_view , name="product_list"),
    path("product/<p_id>/" , product_detail_view , name="product_detail"),
    #category
    path("category/" , category_list_view , name="category_list"),
    path("category/<C_id>/" , category_product_list_view , name="category_product_list"),
    #Vendor
    path("vendors/", vendor_list_view,name="vendors-list"),
    path("vendor/<v_id>/" , vendor_detail_view , name="vendor-list"),
    #Tags
    path("products/tag/<slug:tag_slug>/" , tag_list , name="tag"),
    #Review
    path("ajax-add-review/<p_id>/" , ajax_add_review , name="ajax-add-review"),
    #Search
    path("search/" , search_view , name="search"),
    #Filter
    path("filter-products/" , filter_product , name="filter-product"),
    #Add To Cart
    path("add-to-cart/" , add_to_cart , name="add-to-cart" ),
    #Cart PAGE
    path('cart/', cart_view, name='cart'),
    #Delete Product From Cart
    path('delete-item-from-cart/', delete_item_from_cart, name='delete-item-from-cart'),
    #Update Product From Cart
    path('update-item-from-cart/', update_item_from_cart, name='update-item-from-cart'),
]

core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write Your Review', 'class': 'input'}))
    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

core/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.db.models import Count,Avg
from django.http import HttpResponse,JsonResponse
from taggit.models import Tag
from core.models import Product,Category,Vendor,CartOrder,CartOrderItems,ProductImages,ProductReview,Wishlist,Address
from core.forms import ProductReviewForm
from django.template.loader import render_to_string
from django.contrib import messages
import google.generativeai as genai


def chat(request):
    if request.method == 'POST':
        prompt = request.POST.get('prompt', '')
        # Configure generative AI
        GOOGLE_API_KEY = 'AIzaSyBkeHKZEaz-5N0c3S1B1pU3nw5b4pgeWWM'
        genai.configure(api_key=GOOGLE_API_KEY)
        model = genai.GenerativeModel('gemini-pro')
        response = model.generate_content(prompt)
        result = ''.join([p.text for p in response.candidates[0].content.parts])
        return render(request, 'core/chat.html', {'prompt': prompt, 'result': result})
    return render(request, 'core/chat.html', {})

# Create your views here.
def index(request):
    # product = Product.objects.all()
    product = Product.objects.filter(product_status="published" , featured=True)
    category = Category.objects.all()
    context = {
        "products":product,
        "categories":category,
    }
    return render(request,'core/index.html',context)

def product_list_view(request):
    product = Product.objects.filter(product_status="published")
    context = {
        "products":product,
    }
    return render(request,'core/product-list.html',context) 

def category_list_view(request):
    categories = Category.objects.all()
    context = {
        "categories":categories,
    }
    return render(request,'core/category-list.html',context) 

def category_product_list_view(request,C_id):
    category = Category.objects.get(C_id=C_id)
    products = Product.objects.filter(product_status="published" , category=category)
    context = {
        "category":category,
        "products":products,
    }
    return render(request,"core/category-product-list.html",context)

def vendor_list_view(request):
    vendors = Vendor.objects.all()
    context = {
        "vendors": vendors,
    }
    return render(request,"core/vendor-list.html",context)

def vendor_detail_view(request,v_id):
    vendor = Vendor.objects.get(v_id=v_id)
    products = Product.objects.filter(vendor=vendor,product_status="published" )
    context = {
        "vendor":vendor,
        "products":products,
    }
    return render(request,"core/vendor-detail.html",context)

def product_detail_view(request,p_id):
    
    product = Product.objects.get(p_id=p_id)
    products = Product.objects.filter(category = product.category).exclude(p_id=p_id)
    p_image = product.p_images.all()
    #Getting all reviews related to a product
    reviews = ProductReview.objects.filter(product=product).order_by("-date")
    #Getting average review 
    avrage_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    review_form = ProductReviewForm()
    
    context = {
        "product":product,
        "p_image":p_image,
        "reviews" : reviews,
        "avrage_rating": avrage_rating,
        "review_form":review_form,
        "products":products,
    }
    return render(request,'core/product-detail.html',context)

def tag_list (request , tag_slug=None):
    products = Product.objects.filter(product_status="published").order_by("-id")
    tag = None
    if tag_slug : 
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])
    context = {
        "products":products,
        "tag":tag,
    }
    return render(request,'core/tags.html',context)

def ajax_add_review(request,p_id):
    product = Product.objects.get(pk=p_id)
    user = request.user
    review = ProductReview.objects.create(
        user=user,
        product=product,
        review = request.POST['review'],
        rating = request.POST['rating'],
    )
    context = {
       'user': user.username,
       'review': request.POST['review'],
       'rating': request.POST['rating'],
    }
    avrage_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))
    return JsonResponse(
        {
            'bool' : True,
            'context':context,
            'avrage_reviews':avrage_reviews,
        }
    )
    
def search_view(request):
    query = request.GET.get("q")
    products = Product.objects.filter(title__icontains=query,description__icontains=query).order_by("-date")
    context = {
        "products":products,
        "query":query,
    }
    return render(request,"core/search.html",context)

def filter_product(request):
    categories = request.GET.getlist("category[]")
    vendors = request.GET.getlist("vendor[]")
    products = Product.objects.filter(product_status="published").order_by("-id").distinct()
    if len(categories) > 0 :
        products = products.filter(category__id__in = categories).distinct()
        
    if len(vendors) > 0:
        products = products.filter(vendor__id__in = vendors).distinct()

    data =  render_to_string("core/async/product-list.html", {"products": products })
    return JsonResponse({"data":data})

def add_to_cart(request):
    # Initialiser un dictionnaire vide pour contenir les informations sur le produit à ajouter au panier
    cart_product = {}
    # Remplir le dictionnaire cart_product avec les informations sur le produit à partir de la requête GET
    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'qty': request.GET['qty'],
        'price': request.GET['price'],
        'image': request.GET['image'],
        'p_id': request.GET['p_id'],
    }
    # Vérifier si 'cart_data_obj' existe dans la session
    if 'cart_data_obj' in request.session:
        # Vérifier si l'identifiant du produit existe déjà dans les données du panier
        if str(request.GET['id']) in request.session['cart_data_obj']:
            # Si l'identifiant du produit existe, mettre à jour la quantité du produit existant dans le panier
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = int(cart_product[str(request.GET['id'])]['qty'])
            request.session['cart_data_obj'] = cart_data
        else:
            # Si l'identifiant du produit n'existe pas, ajouter le nouveau produit aux données du panier
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        # Si 'cart_data_obj' n'existe pas dans la session, le créer et ajouter le produit
        request.session['cart_data_obj'] = cart_product
    # Retourner une réponse JSON contenant les données du panier mises à jour et le nombre total d'articles dans le panier
    return JsonResponse({"data": request.session['cart_data_obj'], 'TotalCartItem': len(request.session['cart_data_obj'])})

def cart_view(request):
    cart_total_amount = 0  # Initialiser le montant total du panier
    
    if 'cart_data_obj' in request.session:  # Vérifier si 'cart_data_obj' existe dans la session
        for p_id, item in request.session['cart_data_obj'].items():  # Itérer sur les articles dans les données du panier
            # Calculer le montant total pour chaque article dans le panier
            cart_total_amount += int(item['qty']) * float(item['price'])
        
        # Rendre le template du panier avec les données du panier, le nombre total d'articles et le montant total du panier
        return render(request, "core/cart.html", {
            "cart_data": request.session['cart_data_obj'],
            'TotalCartItem': len(request.session['cart_data_obj']),
            'cart_total_amount': cart_total_amount
        })
    else:
        # Afficher un message d'avertissement si le panier est vide et rediriger vers la page d'accueil
        messages.warning(request, "Your Cart Is Empty")
        return redirect("core:index")

def delete_item_from_cart(request):
    product_id = str(request.GET['id'])  # Récupérer l'identifiant du produit depuis la requête
    
    if 'cart_data_obj' in request.session:  # Vérifier si 'cart_data_obj' existe dans la session
        if product_id in request.session['cart_data_obj']:  # Vérifier si l'identifiant du produit existe dans les données du panier
            cart_data = request.session['cart_data_obj']  # Récupérer les données du panier depuis la session
            del request.session['cart_data_obj'][product_id]  # Supprimer le produit des données du panier
            # Déplacer l'assignation des données du panier en dehors du bloc if interne
            request.session['cart_data_obj'] = cart_data
        
    cart_total_amount = 0  # Initialiser le montant total du panier
    
    if 'cart_data_obj' in request.session:  # Vérifier si 'cart_data_obj' existe toujours dans la session
        for p_id, item in request.session['cart_data_obj'].items():  # Parcourir les articles dans les données du panier
            # Calculer le montant total pour chaque article dans le panier
            cart_total_amount += int(item['qty']) * float(item['price'])
    
    # Rendre le template de la liste de panier mis à jour avec les données du panier modifiées et le montant total du panier
    context = render_to_string("core/async/cart-list.html", {
        "cart_data": request.session['cart_data_obj'],
        'TotalCartItem': len(request.session['cart_data_obj']),
        'cart_total_amount': cart_total_amount
    })
    
    # Retourner les données du panier mises à jour et le nombre total d'articles au format JSON
    return JsonResponse({"data": context, 'TotalCartItem': len(request.session['cart_data_obj'])})

def update_item_from_cart(request):
    # Extrait l'identifiant du produit et la quantité de la requête
    product_id = str(request.GET.get('id', ''))

templates/core/cart.html
{% extends 'partials/base.html'%}
{% block title %}Bi3Smart | Cart Page{% endblock %}
{% load static %}
{% block content %}

{% if messages%}
{% for message in messages%}
    <div class="alert alert-{{message.tags}}">
        <strong>{{message}}</strong>
    </div>
{% endfor %}
{% endif %}
    
<section class="shoping-cart spad" id="cart-list">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="shoping__cart__table">
                    <table>
                        <thead>
                            <tr>
                                <th class="shoping__product">Products</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                                <th>Ref</th>                                
                                <th>Del</th>

                            </tr>
                        </thead>
                        <tbody>
                            {% for product_id,item in cart_data.items%}
                            <tr>
                                <td class="shoping__cart__item">
                                    <img src="{{item.image}}" width="100" height="100" alt="">
                                    <h5><a href="{%url 'core:product_detail' item.p_id %}">{{item.title}}</a></h5>
                                </td>
                                <td class="shoping__cart__price">
                                    {{item.price|floatformat:0}} MAD
                                </td>
                                <td class="shoping__cart__quantity">
                                    <div class="quantity">
                                        <div class="pro-qty">
                                            {% comment %} <span class="dec qtybtn">-</span> {% endcomment %}
                                                <input class="input product-qty-{{product_id}}" type="text" value="{{item.qty}}">
                                            {% comment %} <span class="inc qtybtn">+</span> {% endcomment %}
                                        </div>
                                    </div>
                                </td>
                                <td class="shoping__cart__total">
                                     {% widthratio item.price 1 item.qty %} MAD
                                </td>
                                <td class="action text-center update-product" data-product="{{product_id}}">
                                    <button href="#" class="text-body"><i class="fa fa-refresh" style="color: #3b5998;"></i></button>
                                </td>
                                <td class="action text-center delete-product" data-product="{{product_id}}">
                                   <button href="#" class="text-body"><i class="fa fa-trash" style="color: #3b5998;"></i></button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="shoping__cart__btns">
                    <a href="{% url 'core:product_list'%}" class="primary-btn cart-btn">CONTINUE SHOPPING</a>
                    <a href="#" class="primary-btn cart-btn cart-btn-right"><span class="icon_loading"></span>
                        Upadate Cart</a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="shoping__continue">
                    <div class="shoping__discount">
                        <h5>Discount Codes</h5>
                        <form action="#">
                            <input  class="input" type="text" placeholder="Enter your coupon code">
                            <button type="submit" class="site-btn">APPLY COUPON</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="shoping__checkout">
                    <h5>Cart Total</h5>
                    <ul>
                        <li>Subtotal <span>{{cart_total_amount}} MAD</span></li>
                        <li>Shipping <span>0 MAD</span></li>
                        <li>Total <span>{{cart_total_amount}} MAD</span></li>
                    </ul>
                    <a href="#" class="primary-btn">PROCEED TO CHECKOUT</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
 

templates/core/category-list.html
{% extends 'partials/base.html'%}
{% block title %}Bi3Smart | Categories Page{% endblock %}
{% load static %}
{% block content %}

  {% if messages%}
  {% for message in messages%}
      <div class="alert alert-{{message.tags}}">
          <strong>{{message}}</strong>
      </div>
  {% endfor %}
  {% endif %}
  
  <!-- SECTION -->
  <div class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <!-- shop -->
        <div class="col-md-4 col-xs-6">
          <div class="shop">
            <div class="shop-img">
              <img src="./img/shop01.png" alt="" />
            </div>
            <div class="shop-body">
              <h3>Laptop<br />Collection</h3>
              <a href="#" class="cta-btn"
                >Shop now <i class="fa fa-arrow-circle-right"></i
              ></a>
            </div>
          </div>
        </div>
        <!-- /shop -->

        <!-- shop -->
        <div class="col-md-4 col-xs-6">
          <div class="shop">
            <div class="shop-img">
              <img src="./img/shop03.png" alt="" />
            </div>
            <div class="shop-body">
              <h3>Accessories<br />Collection</h3>
              <a href="#" class="cta-btn"
                >Shop now <i class="fa fa-arrow-circle-right"></i
              ></a>
            </div>
          </div>
        </div>
        <!-- /shop -->

        <!-- shop -->
        <div class="col-md-4 col-xs-6">
          <div class="shop">
            <div class="shop-img">
              <img src="./img/shop02.png" alt="" />
            </div>
            <div class="shop-body">
              <h3>Cameras<br />Collection</h3>
              <a href="#" class="cta-btn"
                >Shop now <i class="fa fa-arrow-circle-right"></i
              ></a>
            </div>
          </div>
        </div>
        <!-- /shop -->
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /SECTION -->

  <!-- SECTION -->
  <div class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <!-- section title -->
        <div class="col-md-12">
          <div class="section-title">
            <h3 class="title">Categories</h3>
            <p class="product-price">
              We found {{categories.count}} categorie{{categories.count|pluralize:"s"}}
          </p>
          </div>
        </div>
        <!-- /section title -->

        <!-- Products tab & slick -->
        <div class="col-md-12">
          <div class="row">
            <div class="products-tabs">
              <!-- tab -->
              <div id="tab1" class="tab-pane active">
                <div class="products-slick" data-nav="#slick-nav-1">
                  <!-- product -->
                  {% for category in categories%}
                        <div class="product">
                          <a href="{% url 'core:category_product_list' category.C_id%}">

                          <div class="product-img">
                            <img src="{{category.image.url}}" alt="" />
                            <div class="product-label">
                              <span class="new">Category</span>
                            </div>
                          </div>
                          <div class="product-body">
                            <p class="product-category">{{category.title}}</p>
                            <h3 class="product-name">
                              {{category.title}}
                            </h3>
                            <h4 class="product-price">
                              {{category.category.count}} Product{{category.category.count|pluralize:"s"}}
                            </h4>
                          </div>
                        </a>
                        </div>
                  {% endfor%}
                  <!-- /product -->
                </div>
                <div id="slick-nav-1" class="products-slick-nav"></div>
              </div>
              <!-- /tab -->
            </div>
          </div>
        </div>
        <!-- Products tab & slick -->
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /SECTION -->
{% endblock content %}

templates/core/chat.html
{% extends 'partials/base.html'%}
{% block title %}Bi3Smart | Chat Page{% endblock %}
{% load static %}
{% block content %}

<div id="newsletter" class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <div class="col-md-12">
          <div class="newsletter">
            <p>Helper <strong> Bi3 Smart</strong></p>
            <form method="post">
                {% csrf_token %}
                <input class="input" id="prompt" name="prompt" type="text" value="{{ prompt }}" placeholder="Enter Your Question"/>
                <button type="submit" class="newsletter-btn">
                    <i class="fa fa-chat"></i> Send
                </button>
            </form>
            {% if result %}
                <p class="mt-3">Bi3Smart : {{ result }}</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/core/index.html
{% extends 'partials/base.html'%}
{% block title %}Bi3Smart | Home Page{% endblock %}
{% load static %}
{% block content %}

    {% if messages%}
    {% for message in messages%}
        <div class="alert alert-{{message.tags}}">
            <strong>{{message}}</strong>
        </div>
    {% endfor %}
    {% endif %}
    
    <!-- SECTION -->
    <div class="section">
      <!-- container -->
      <div class="container">
        <!-- row -->
        <div class="row">
          {% for category in categories%}
          <!-- shop -->
          <div class="col-md-4 col-xs-6">
            <div class="shop">
              <a href="{% url 'core:category_product_list' category.C_id%}">
                <div class="shop-img">
                  <img src="{{category.image.url}}" alt="" />
                </div>
                <div class="shop-body">
                  <h3>{{category.title}}</h3>
                  <a href="{% url 'core:category_product_list' category.C_id%}" class="cta-btn"
                    >Shop now <i class="fa fa-arrow-circle-right"></i
                  ></a>
                </div>
              </a>
            </div>
          </div>
          <!-- /shop -->
          {%endfor%}

        </div>
        <!-- /row -->
      </div>
      <!-- /container -->
    </div>
    <!-- /SECTION -->

    <!-- SECTION -->
    <div class="section">
      <!-- container -->
      <div class="container">
        <!-- row -->
        <div class="row">
          <!-- section title -->
          <div class="col-md-12">
            <div class="section-title">
              <h3 class="title">New Products</h3>
              <div class="section-nav">
                <ul class="section-tab-nav tab-nav">
                  {% for category in categories%}
                    <li><a data-toggle="tab" href="#tab1">{{category.title}}</a></li>
                  {%endfor%}
                </ul>
              </div>
            </div>
          </div>
          <!-- /section title -->

          <!-- Products tab & slick -->
          <div class="col-md-12">
            <div class="row">
              <div class="products-tabs">
                <!-- tab -->
                <div id="tab1" class="tab-pane active">
                  <div class="products-slick" data-nav="#slick-nav-1">
                    <!-- product -->
                    {% for product in products%}
                    <div class="product">
                      <a href="{% url 'core:product_detail' product.p_id%}">
                      <div class="product-img">
                        <img src="{{product.image.url}}" alt="" />
                        <div class="product-label">
                          <span class="sale">-{{product.get_precentage|floatformat:0}}%</span>
                          <span class="new">NEW</span>
                        </div>
                      </div>
                      <div class="product-body">
                        <p class="product-category">{{product.category.title}}</p>
                        <h3 class="product-name">
                          <a href="{% url 'core:product_detail' product.p_id%}">{{product.title}}</a>
                        </h3>
                        <h4 class="product-price"> <span class="current-product-price-{{product.id}}">{{product.price|floatformat:0}}</span> MAD <del class="product-old-price">{{product.old_price|floatformat:0}} MAD</del></h4>
                        <div class="product-rating">
                          <i class="fa fa-star"></i>
                          <i class="fa fa-star"></i>
                          <i class="fa fa-star"></i>
                          <i class="fa fa-star"></i>
                          <i class="fa fa-star"></i>
                        </div>
                        <div class="product-btns">
                          <button class="add-to-wishlist">
                            <i class="fa fa-heart-o"></i
                            ><span class="tooltipp">add to wishlist</span>
                          </button>
                          <button class="add-to-compare">
                            <i class="fa fa-exchange"></i
                            ><span class="tooltipp">add to compare</span>
                          </button>
                          <button class="quick-view">
                            <i class="fa fa-eye"></i
                            ><span class="tooltipp">quick view</span>
                          </button>
                        </div>
                      </div>
                      <div class="add-to-cart">
                        <input type="hidden" value="1" name="" id="product-quantity" class="product-quantity-{{product.id}}">
                        <input type="hidden" class="product-pid-{{product.id}}" id="{{product.id}}" value="{{product.p_id}}">
                        <input type="hidden" class="product-id-{{product.id}}" id="{{product.id}}" value="{{product.id}}">
                        <input type="hidden" class="product-image-{{product.id}}" id="{{product.image.url}}" value="{{product.image.url}}">
                         <input type="hidden" class="product-title-{{product.id}}" id="{{product.title}}" value="{{product.title}}">
                        <button class="add-to-cart-btn" id="add-to-cart-btn" data-index="{{product.id}}">
                          <i class="fa fa-shopping-cart" id="add-to-cart-btn"></i> add to cart
                        </button>
                      </div>
                    </a>
                    </div>
                    {% endfor%}
                    <!-- /product -->
                  </div>
                  <div id="slick-nav-1" class="products-slick-nav"></div>
                </div>
                <!-- /tab -->
              </div>
            </div>
          </div>
          <!-- Products tab & slick -->
        </div>
        <!-- /row -->
      </div>
      <!-- /container -->
    </div>
    <!-- /SECTION -->

    <!-- HOT DEAL SECTION -->
    <div id="hot-deal" class="section">
      <!-- container -->
      <div class="container">
        <!-- row -->
        <div class="row">
          <div class="col-md-12">
            <div class="hot-deal">
              <ul class="hot-deal-countdown">
                <li>
                  <div>
                    <h3>02</h3>
                    <span>Days</span>
                  </div>
                </li>
                <li>
                  <div>
                    <h3>10</h3>
                    <span>Hours</span>
                  </div>
                </li>
                <li>
                  <div>
                    <h3>34</h3>
                    <span>Mins</span>
                  </div>
                </li>
                <li>
                  <div>
                    <h3>60</h3>
                    <span>Secs</span>
                  </div>
                </li>
              </ul>
              <h2 class="text-uppercase">hot deal this week</h2>
              <p>New Collection Up to 50% OFF</p>
              <a class="primary-btn cta-btn" href="#">Shop now</a>
            </div>
          </div>
        </div>
        <!-- /row -->
      </div>
      <!-- /container -->
    </div>
    <!-- /HOT DEAL SECTION -->
{% endblock content %}
 