Bi3Smart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/",include("userauths.urls")),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import index,chat,update_item_from_cart,delete_item_from_cart,cart_view,add_to_cart,filter_product,search_view,ajax_add_review,tag_list,product_list_view,category_list_view,category_product_list_view, vendor_detail_view,vendor_list_view,product_detail_view
app_name= "core"

urlpatterns = [
    #chatbot
    path('chat/', chat, name='chat'),

    #HomePage
    path("",index , name="index"),
    #Product
    path("products/" , product_list_view , name="product_list"),
    path("product/<p_id>/" , product_detail_view , name="product_detail"),
    #category
    path("category/" , category_list_view , name="category_list"),
    path("category/<C_id>/" , category_product_list_view , name="category_product_list"),
    #Vendor
    path("vendors/", vendor_list_view,name="vendors-list"),
    path("vendor/<v_id>/" , vendor_detail_view , name="vendor-list"),
    #Tags
    path("products/tag/<slug:tag_slug>/" , tag_list , name="tag"),
    #Review
    path("ajax-add-review/<p_id>/" , ajax_add_review , name="ajax-add-review"),
    #Search
    path("search/" , search_view , name="search"),
    #Filter
    path("filter-products/" , filter_product , name="filter-product"),
    #Add To Cart
    path("add-to-cart/" , add_to_cart , name="add-to-cart" ),
    #Cart PAGE
    path('cart/', cart_view, name='cart'),
    #Delete Product From Cart
    path('delete-item-from-cart/', delete_item_from_cart, name='delete-item-from-cart'),
    #Update Product From Cart
    path('update-item-from-cart/', update_item_from_cart, name='update-item-from-cart'),
]

userauths/urls.py
from django.urls import path
from userauths import views
app_name = "userauths"
urlpatterns = [
    path("sign-up/", views.register_view,name="sign-up"),
    path("sign-in/", views.login_view,name="sign-in"),
    path("sign-out/", views.logout_view,name="sign-out"),
]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=100)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']
    def __str__(self):
        return self.username

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User
class UserRegisterForm(UserCreationForm):
    username = forms.CharField( widget=forms.TextInput(attrs={"placeholder": "Username", "class": "form-control bg-transparent" , "name" : "Username"}))
    email = forms.EmailField( widget=forms.TextInput(attrs={"placeholder": "Email", "class": "form-control bg-transparent" , "name" : "Email"}))
    password1 = forms.CharField( widget=forms.PasswordInput(attrs={"placeholder": "Password", "class": "form-control bg-transparent" , "name" : "password"}))
    password2 = forms.CharField( widget=forms.PasswordInput(attrs={"placeholder": "Repeat Password", "class": "form-control bg-transparent" , "name" : "RepeatPassword"}))

    class Meta:
        model = User
        fields = ['username','email']

userauths/views.py
from django.shortcuts import render,redirect
from userauths.forms import UserRegisterForm
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from django.conf import settings
from userauths.models import User
# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            newuser = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request,f"Hey {username} , Your Account Was Created Succesfully.")
            newuser = authenticate(
                username=form.cleaned_data['email'],
                password=form.cleaned_data['password1'],                                   
            )
            login(request,newuser)
            return redirect("core:index")
    else :
        form = UserRegisterForm()

    context = {
        'form':form,
    }
    return render(request , "userauths/sign-up.html", context)

def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request,f"Hey you are already logged In.")
        return redirect("core:index")
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email , password=password)
            if user is not None :
                login(request,user)
                messages.success(request,f"Hey You are logged in.")
                return redirect("core:index")
            else:
                messages.warning(request,f"User does not exist. Create an account.")
        except:
            messages.warning(request,f"User with {email} does not exist")
   
    return render(request, "userauths/sign-in.html")

def logout_view(request):
    logout(request)
    messages.success(request,f"You logged out.")
    return redirect("userauths:sign-in")

templates/userauths/sign-in.html
{% load static %}
<html lang="en">
	<head>
		<title>Bi3Smart | Sign In</title>
		<meta charset="utf-8" />
		<link rel="canonical" href="https://preview.keenthemes.com/metronic8" />
        <link rel="icon" href="{% static "assets/img/logo.png" %}" type="image/x-icon" />
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700" />
		<link href="{% static "assets_admin/plugins/global/plugins.bundle.css" %}" rel="stylesheet" type="text/css" />
		<link href="{% static "assets_admin/css/style.bundle.css" %}" rel="stylesheet" type="text/css" />
	</head>
	<body id="kt_body" class="app-blank bgi-size-cover bgi-position-center">
		<script>var defaultThemeMode = "light"; var themeMode; if ( document.documentElement ) { if ( document.documentElement.hasAttribute("data-bs-theme-mode")) { themeMode = document.documentElement.getAttribute("data-bs-theme-mode"); } else { if ( localStorage.getItem("data-bs-theme") !== null ) { themeMode = localStorage.getItem("data-bs-theme"); } else { themeMode = defaultThemeMode; } } if (themeMode === "system") { themeMode = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"; } document.documentElement.setAttribute("data-bs-theme", themeMode); }</script>
		<div class="d-flex flex-column flex-root" id="kt_app_root">
			<style>body { background-image: url('{% static "assets_admin/media/auth/bg10.jpeg" %}'); } [data-bs-theme="dark"] body { background-image: url('{% static "assets_admin/media/auth/bg10-dark.jpeg" %}'); }</style>
            <div class="container mt-5 mb-5">
                <div class="d-flex align-items-center justify-content-center">
                    <div class="bg-body d-flex flex-column flex-center rounded-4 w-md-600px p-10">
                        <div class="d-flex flex-center flex-column align-items-stretch h-lg-100 w-md-400px">
                            <div class="d-flex flex-center flex-column-fluid pb-15 pb-lg-20">
                                <form class="form w-100" novalidate="novalidate" id="kt_sign_up_form" action="#" method="POST">
                                        {% csrf_token %}
                                        <div class="text-center mb-11">
                                            <h1 class="text-dark fw-bolder mb-3">Sign In</h1>
                                            <div class="text-gray-500 fw-semibold fs-6">Bi3 Smart</div>
                                        </div>
                                        <div class="row g-3 mb-9">
                                            <div class="col-md-12">
                                                <a href="#" class="btn btn-flex btn-outline btn-text-gray-700 btn-active-color-primary bg-state-light flex-center text-nowrap w-100">
                                                    <img alt="Logo" src="{% static "assets_admin/media/svg/brand-logos/google-icon.svg" %}" class="h-15px me-3" />Sign in with Google</a>
                                            </div>
                                        </div>
                                        <div class="separator separator-content my-14">
                                            <span class="w-125px text-gray-500 fw-semibold fs-7">Or with email</span>
                                        </div>
                                        {% if messages%}
                                            {% for message in messages%}
                                                <div class="alert alert-{{message.tags}}">
                                                    <strong>{{message}}</strong>
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                        
                                        <div class="fv-row mb-8">
                                            <input type="email" required name="email" placeholder="Username or Email" class="form-control bg-transparent"/>
                                        </div> 
                                        <div class="fv-row mb-8">
                                            <input type="password" required name="password" placeholder="Password" class="form-control bg-transparent"/>
                                        </div> 
                                        <div class="fv-row mb-8">
                                            <label class="form-check form-check-inline">
                                                <input class="form-check-input" type="checkbox" name="toc" value="1" />
                                                <span class="form-check-label fw-semibold text-gray-700 fs-base ms-1">Remember Me</span>
                                            </label>
                                        </div>
                                        <div class="d-grid mb-10">
                                            <button type="submit" name="Sign up" id="kt_sign_up_submit" class="btn btn-primary">
                                                <span class="indicator-label">Sign up</span>
                                            </button>
                                        </div>
                                        <div class="text-gray-500 text-center fw-semibold fs-6">
                                            <a href="#" class="link-primary fw-semibold">Forgot password?</a>
                                        </div>
                                        <div class="text-gray-500 text-center fw-semibold fs-6">You Dont have an Account?
                                            <a href="{% url 'userauths:sign-up'%}" class="link-primary fw-semibold">Sign up</a>
                                        </div>
                                    </form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script src="{% static "assets_admin/plugins/global/plugins.bundle.js" %}"></script>
		<script src="{% static "assets_admin/js/scripts.bundle.js" %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <script>
            setTimeout (() => {
                $(".alert").alert("close")
            },3000
            )
        </script>
	</body>
</html>

templates/userauths/sign-up.html
{% load static %}
<html lang="en">
	<head>
		<title>Bi3Smart | Sign Up</title>
		<meta charset="utf-8" />
		<link rel="canonical" href="https://preview.keenthemes.com/metronic8" />
        <link rel="icon" href="{% static "assets/img/logo.png" %}" type="image/x-icon" />
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700" />
		<link href="{% static "assets_admin/plugins/global/plugins.bundle.css" %}" rel="stylesheet" type="text/css" />
		<link href="{% static "assets_admin/css/style.bundle.css" %}" rel="stylesheet" type="text/css" />
	</head>
	<body id="kt_body" class="app-blank bgi-size-cover bgi-position-center">
		<script>var defaultThemeMode = "light"; var themeMode; if ( document.documentElement ) { if ( document.documentElement.hasAttribute("data-bs-theme-mode")) { themeMode = document.documentElement.getAttribute("data-bs-theme-mode"); } else { if ( localStorage.getItem("data-bs-theme") !== null ) { themeMode = localStorage.getItem("data-bs-theme"); } else { themeMode = defaultThemeMode; } } if (themeMode === "system") { themeMode = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"; } document.documentElement.setAttribute("data-bs-theme", themeMode); }</script>
		<div class="d-flex flex-column flex-root" id="kt_app_root">
			<style>body { background-image: url('{% static "assets_admin/media/auth/bg10.jpeg" %}'); } [data-bs-theme="dark"] body { background-image: url('{% static "assets_admin/media/auth/bg10-dark.jpeg" %}'); }</style>
            <div class="container mt-5 mb-5">
                <div class="d-flex align-items-center justify-content-center">
                    <div class="bg-body d-flex flex-column flex-center rounded-4 w-md-600px p-4">
						<div class="d-flex flex-center flex-column align-items-stretch h-lg-100 w-md-400px">
    							<div class="d-flex flex-center flex-column-fluid pb-8 pb-lg-10">
                                    <form class="form w-100" novalidate="novalidate" id="kt_sign_up_form" action="#" method="POST">
                                        {% csrf_token %}
                                        <div class="text-center mb-11">
                                            <h1 class="text-dark fw-bolder mb-3">Sign Up</h1>
                                            <div class="text-gray-500 fw-semibold fs-6">Bi3 Smart</div>
                                        </div>
                                        <div class="row g-3 mb-9">
                                            <div class="col-md-12">
                                                <a href="#" class="btn btn-flex btn-outline btn-text-gray-700 btn-active-color-primary bg-state-light flex-center text-nowrap w-100">
                                                    <img alt="Logo" src="{% static "assets_admin/media/svg/brand-logos/google-icon.svg" %}" class="h-15px me-3" />Sign in with Google</a>
                                            </div>
                                        </div>
                                        <div class="separator separator-content my-14">
                                            <span class="w-125px text-gray-500 fw-semibold fs-7">Or with email</span>
                                        </div>
                                        {% if messages%}
                                            {% for message in messages%}
                                                <div class="alert alert-{{message.tags}}">
                                                    <strong>{{message}}</strong>
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                        
                                        <div class="fv-row mb-8">
                                            {{form.username}}
                                            {% if form.username.errors %}
                                                {% for error in form.username.errors %}
                                                    <div class="alert alert-danger">{{ error }}</div>
                                                {% endfor %}
                                        {% endif %}
                                        </div>
                                        <div class="fv-row mb-8">
                                            {{form.email}}
                                            {% if form.email.errors %}
                                                {% for error in form.email.errors %}
                                                    <div class="alert alert-danger">{{ error }}</div>
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                        <div class="fv-row mb-8" data-kt-password-meter="true">
                                            <div class="mb-1">
                                                <div class="position-relative mb-3">
                                                    {{form.password1}}
                                                    <span class="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2" data-kt-password-meter-control="visibility">
                                                        <i class="bi bi-eye-slash fs-2"></i>
                                                        <i class="bi bi-eye fs-2 d-none"></i>
                                                    </span>
                                                    {% if form.password1.errors %}
                                                            {% for error in form.password1.errors %}
                                                                <div class="alert alert-danger">{{ error }}</div>
                                                            {% endfor %}
                                                    {% endif %}
                                                </div>
                                                <div class="d-flex align-items-center mb-3" data-kt-password-meter-control="highlight">
                                                    <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
                                                    <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
                                                    <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
                                                    <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px"></div>
                                                </div>
                                            </div>
                                            <div class="text-muted">Use 8 or more characters with a mix of letters, numbers & symbols.</div>
                                        </div>
                                        <div class="fv-row mb-8">
                                            {{form.password2}}
                                            {% if form.password2.errors %}
                                                {% for error in form.password2.errors %}
                                                    <div class="alert alert-danger">{{ error }}</div>
                                                {% endfor %}
                                            {% endif %}
                                        </div>
                                        <div class="fv-row mb-8">
                                            <label class="form-check form-check-inline">
                                                <input class="form-check-input" type="checkbox" name="toc" value="1" />
                                                <span class="form-check-label fw-semibold text-gray-700 fs-base ms-1">I Accept the
                                                    <a href="#" class="ms-1 link-primary">Terms</a></span>
                                            </label>
                                        </div>
                                        <div class="d-grid mb-10">
                                            <button type="submit" name="Sign up" id="kt_sign_up_submit" class="btn btn-primary">
                                                <span class="indicator-label">Sign up</span>
                                            </button>
                                        </div>
                                        <div class="text-gray-500 text-center fw-semibold fs-6">Already have an Account?
                                            <a href="{% url 'userauths:sign-in'%}" class="link-primary fw-semibold">Sign in</a></div>
                                    </form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script src="{% static "assets_admin/plugins/global/plugins.bundle.js" %}"></script>
		<script src="{% static "assets_admin/js/scripts.bundle.js" %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <script>
            setTimeout (() => {
                $(".alert").alert("close")
            },3000
            )
        </script>
	</body>
</html>